### ISSUE TITLE
java.lang.NullPointerException thrown when Kumulos is being intialized. 

### ISSUE THREAD

**Issue by LosoncziTamas** [Kumulos/KumulosSdkUnity#7]
Hi!

I get a crash with the following stacktrace when I open the Unity app I'm working on:

```NullReferenceException: Object reference not set to an instance of an object.
05-12 12:12:34.721 10673 10762 E Unity   :   at KumulosSdk.Kumulos.PollPendingPush () [0x00000] in <00000000000000000000000000000000>:0 
05-12 12:12:34.721 10673 10762 E Unity   :   at KumulosSdk.Kumulos.Awake () [0x00000] in <00000000000000000000000000000000>:0 
05-12 12:12:34.721 10673 10762 E Unity   : 
05-12 12:12:34.742 10673 10762 E Unity   : AndroidJavaException: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.concurrent.Future java.util.concurrent.ExecutorService.submit(java.lang.Runnable)' on a null object reference
05-12 12:12:34.742 10673 10762 E Unity   : java.lang.NullPointerException: Attempt to invoke interface method 'java.util.concurrent.Future java.util.concurrent.ExecutorService.submit(java.lang.Runnable)' on a null object reference
05-12 12:12:34.742 10673 10762 E Unity   : 	at com.kumulos.android.Kumulos.pushRegister(Kumulos.java:502)
05-12 12:12:34.742 10673 10762 E Unity   : 	at com.kumulos.android.unity.UnityProxy.pushRegUnreg(UnityProxy.java:135)
05-12 12:12:34.742 10673 10762 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
05-12 12:12:34.742 10673 10762 E Unity   : 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
05-12 12:12:34.742 10673 10762 E Unity   : 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
05-12 12:12:34.742 10673 10762 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:103)
05-12 12:12:34.742 10673 10762 E Unity   : 	at android.os.Looper.loop(Looper.java:214)
05-12 12:12:34.742 10673 10762 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
05-12 12:12:34.742 10673 10762 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
05-12 12:12:34.742 10673 10762 E Unity   :   at UnityEngine.AndroidJa
```

I've followed the user [guide](https://docs.kumulos.com/developer-guide/sdk-reference/unity/). And here is the relevant unity code:

```csharp
    public class KumulosInit : MonoBehaviour
    {
        private void Awake()
        {
            var config = (new Config.Builder(ApiKey, SecretKey))
                .Build();

            Kumulos.Initialize(config);

            // Uncomment the following to register for push notifications
            Kumulos.Shared.PushRegister();

            // Uncomment to handle push message receipt
            Kumulos.Shared.OnPushReceived += (PushMessage message) =>
            {
                Debug.Log("Push message received");
            };
        
            Debug.Log("Kumulos: " + Kumulos.Shared.InstallId);
        
            var attributes = new Dictionary<string, object>();
            attributes.Add("single_player", "played");
            attributes.Add("stage", 11);

            Kumulos.Shared.AssociateUserWithInstall("test", attributes);
        }
    }
```

It seems that the SDK itself is not initialized yet when I invoke `Kumulos.Shared.PushRegister()` (since the [ExecutorService](https://github.com/Kumulos/KumulosSdkAndroid/blob/master/kumulos/src/main/java/com/kumulos/android/Kumulos.java#L526) is null).

Please let me know If I missed anything.
Thanks!

**Comment by cgwyllie** [comment]
Hi @LosoncziTamas,

Thanks for contacting us about this issue!

Can I just ask for some further information:

- Unity version
- SDK version
- Android tools version

It sounds like it's possible the Kumulos Android library hasn't linked correctly in your exported Android project. Could you maybe double-check that the appropriate gradle templates are overridden as documented?

We'd be happy to assist further, and perhaps the best way to proceed would be to email support@kumulos.com and we'll create a ticket for you.

Kind regards,
  Chris

**Comment by cgwyllie** [comment]
Hi @LosoncziTamas, are you still experiencing any trouble with this?

**Comment by LosoncziTamas** [comment]
Hi @cgwyllie, you can close this ticket. I managed to solve the problem. Thank you for your time!
